[package]
name = "winGrep"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = {version = "4.5.53", features = ["derive"]}
colored = "3.0.0"
memchr = "2.7.6"
memmap2 = "0.9.9"
memmem = "0.1.1"
mmap = "0.1.1"
rayon = "1.11.0"
regex = "1.12.2"
walkdir = "2.5.0"
